import { test, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { scryptSync } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { sampleProfiles } from '../data.js';
import { defaultAvatar } from '../avatar-schema.js';
const backendURL = 'http://127.0.0.1:4175';
test.describe.configure({ mode: 'serial' });
const password = 'browser-test-password';
let server, folder;
test.beforeAll(async () => {
  folder = mkdtempSync(join(tmpdir(), 'hall-browser-'));
  server = spawn('bun', ['scripts/serve-backend.ts'], { env: { ...process.env, PORT: '4175', HALL_DB_PATH: join(folder, 'test.db'), HALL_ADMIN_PASSWORD_HASH: `scrypt:test-salt:${scryptSync(password, 'test-salt', 64).toString('hex')}`, HALL_ALLOWED_ORIGINS: 'http://127.0.0.1:4173' }, stdio: 'ignore' });
  await expect.poll(async () => { try { return (await fetch(`${backendURL}/api/hall?view=health`)).status; } catch { return 0; } }).toBe(200);
});
test.afterAll(async () => { if (server && server.exitCode === null) { server.kill(); await new Promise(resolve => server.once('exit', resolve)); } if (folder) rmSync(folder, { recursive: true, force: true }); });
async function call(action, values = {}) { const r = await fetch(`${backendURL}/api/hall`, { method: 'POST', body: JSON.stringify({ action, ...values }) }); return await r.json(); }

test('Avatartion studio lets residents customize, download and use an avatar', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Avatar studio', exact: true }).click();
  const before = await page.locator('#studio-preview').getAttribute('src');
  await page.getByRole('button', { name: 'Hair 5', exact: true }).click();
  expect(await page.locator('#studio-preview').getAttribute('src')).not.toBe(before);
  await page.getByRole('button', { name: 'Outfit', exact: true }).click();
  await page.getByRole('button', { name: 'Outfit 9', exact: true }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save SVG' }).click();
  expect((await downloadPromise).suggestedFilename()).toBe('my-hall-avatar.svg');
  expect(await page.locator('#avatar-editor img').evaluateAll(imgs => imgs.every(img => img.complete && img.naturalWidth > 0))).toBe(true);
  await page.screenshot({ path: 'evidence/avatar-studio.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.locator('#avatar-dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.screenshot({ path: 'evidence/avatar-studio-mobile.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Use this avatar' }).click();
  await expect(page.locator('#join-dialog')).toBeVisible();
  await expect(page.locator('#join-dialog [name=xhs]')).toBeVisible();
  await expect(page.locator('#join-dialog [name=linkedin]')).toBeVisible();
});

test('real database flow: submit, admin edit/publish, refresh, social links and archive', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const sessionToken = (await call('login', { password })).token;
  for (const [index, sample] of sampleProfiles.slice(0, 6).entries()) {
    const profile = { ...sample, consent: true, avatarConfig: { ...defaultAvatar, hair: index + 1, outfit: index + 3 } };
    const result = await call('submit', { requestId: crypto.randomUUID(), profile });
    if (index < 2) await call('publish', { id: result.id, version: 1, sessionToken });
    if (index === 5) await call('archive', { id: result.id, version: 1, sessionToken });
  }
  await page.addInitScript(url => localStorage.setItem('common-ground:settings', JSON.stringify({ hallName: 'Common Ground', backendUrl: url, feedUrl: '', formUrl: '' })), backendURL);
  await page.goto('/');
  await expect(page.locator('#profile-grid .profile-card')).toHaveCount(0);
  await page.getByRole('button', { name: 'Join the wall', exact: true }).click();
  for (const [name, value] of Object.entries({ name: 'Taylor Park', curriculum: 'Psychology', intro: 'A movie fan who loves hiking.', help: 'Research and essay feedback', meet: 'Film-night friends', handle: 'taylorpark', xhs: 'https://www.xiaohongshu.com/user/profile/abc123', linkedin: 'https://www.linkedin.com/in/taylor-park' })) await page.locator(`#join-form [name=${name}]`).fill(value);
  await page.locator('#join-form [name=consent]').check();
  await page.getByRole('button', { name: 'Submit for approval' }).click();
  await expect(page.locator('#toast')).toContainText('Introduction received');
  await page.getByRole('button', { name: 'Refresh wall', exact: true }).first().click();
  await expect(page.locator('#profile-grid .profile-card')).toHaveCount(2);
  await expect(page.locator('#profile-grid')).not.toContainText('Taylor Park');
  await page.getByRole('button', { name: 'Admin board' }).click();
  await page.locator('#admin-login-form [name=password]').fill(password);
  await page.getByRole('button', { name: 'Sign in to your hall' }).click();
  await expect(page.locator('#admin-workspace')).toBeVisible();
  await expect(page.locator('#pending-total')).toHaveText('4');
  await page.locator('#toast').evaluate(el => el.hidden = true);
  await page.screenshot({ path: 'evidence/admin-board.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'evidence/admin-board-mobile.png', animations: 'disabled' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('.admin-row').filter({ hasText: 'Taylor Park' }).getByRole('button', { name: 'Review' }).click();
  await page.locator('#admin-edit-form [name=intro]').fill('A movie fan, hiker and matcha enthusiast.');
  await page.locator('#admin-edit-form [name=featured]').check();
  await page.getByRole('button', { name: 'Save profile changes' }).click();
  await expect(page.locator('#toast')).toContainText('Profile changes saved');
  await page.locator('#toast').evaluate(el => el.hidden = true);
  await page.screenshot({ path: 'evidence/admin-review.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Approve & publish' }).click();
  await expect(page.locator('#published-total')).toHaveText('3');
  await page.getByRole('button', { name: 'Back to wall' }).click();
  await expect(page.locator('#profile-grid .profile-card')).toHaveCount(2);
  await page.getByRole('button', { name: 'Refresh wall', exact: true }).first().click();
  await expect(page.locator('#profile-grid .profile-card')).toHaveCount(3);
  const card = page.locator('#profile-grid .profile-card').first();
  await expect(card).toContainText('Taylor Park');
  await expect(card).toContainText('matcha enthusiast');
  await expect(card.getByRole('link', { name: 'Find Taylor Park on XHS' })).toHaveAttribute('href', 'https://www.xiaohongshu.com/user/profile/abc123');
  await expect(card.getByRole('link', { name: 'Find Taylor Park on LinkedIn' })).toHaveAttribute('href', 'https://www.linkedin.com/in/taylor-park');
  await page.getByRole('button', { name: 'Admin board' }).click();
  await expect(page.locator('#admin-workspace')).toBeVisible();
  await page.locator('[data-admin-status=published]').click();
  await page.locator('.admin-row').filter({ hasText: 'Taylor Park' }).getByRole('button', { name: 'Manage' }).click();
  await page.getByRole('button', { name: 'Archive profile', exact: true }).click();
  await expect(page.locator('#archived-total')).toHaveText('2');
  await page.getByRole('button', { name: 'Back to wall' }).click();
  await expect(page.locator('#profile-grid .profile-card')).toHaveCount(3);
  await page.getByRole('button', { name: 'Refresh wall', exact: true }).first().click();
  await expect(page.locator('#profile-grid .profile-card')).toHaveCount(2);
  expect(errors).toEqual([]);
});
